apiVersion: v1
kind: Pod
metadata:
  name: low-pod-1
spec:
  priorityClassName: low-priority
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "250m"
      limits:
        cpu: "250m"
---
apiVersion: v1
kind: Pod
metadata:
  name: low-pod-2
spec:
  priorityClassName: low-priority
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "250m"
      limits:
        cpu: "250m"