### Example: `service-account.yaml`

apiVersion: v1                  # The Kubernetes API version for ServiceAccounts is "v1"
kind: ServiceAccount            # We are creating a resource of type ServiceAccount
metadata:                        # Metadata contains identifying information
  name: my-service-account      # The unique name of the ServiceAccount
  annotations:
    kubernetes.io/service-account.name: my-service-account