apiVersion: v1
kind: Pod
metadata:
  name: pod-exceed
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: "3"             # ❌ exceeds requests.cpu limit (2)
          memory: "6Gi"        # ❌ exceeds requests.memory limit (4Gi)
        limits:
          cpu: "6"             # ❌ exceeds limits.cpu (4)
          memory: "10Gi"       # ❌ exceeds limits.memory (8Gi)
