# vpa.yaml
apiVersion: autoscaling.k8s.io/v1        # Kubernetes API version for VPA
kind: VerticalPodAutoscaler              # Resource type: VerticalPodAutoscaler
metadata:
  name: nginx-vpa                        # Unique name of the VPA object

spec:
  targetRef:                             # Reference to the target workload the VPA manages
    apiVersion: apps/v1                  # API version of the target resource
    kind: Deployment                     # Target resource kind (Deployment, StatefulSet, etc.)
    name: nginx-deployment               # Name of the Deployment to scale vertically

  updatePolicy:
    updateMode: "Auto"                   # VPA update mode
                                          # Options:
                                          #   Off     → Do not update Pods automatically
                                          #   Initial → Set recommended requests only at Pod creation
                                          #   Auto    → Continuously update Pods with new recommendations
                                          #   Recreate→ Recreate Pods when recommendations change

