apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
  - name: init-wait
    image: busybox
    command: ['sh', '-c', 'echo "Initializing..."; sleep 5']
  containers:
  - name: app
    image: nginx
    ports:
    - containerPort: 80