apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev    # Name of the namespace were the pod will be created
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80