### Example: `pv-with-storage-capacity.yaml`

apiVersion: v1                  # The Kubernetes API version for Persistent Volumes is "v1"
kind: PersistentVolume           # We are creating a resource of type PersistentVolume
metadata:                        # Metadata contains identifying information
  name: my-storage-pv            # The unique name of the PersistentVolume
spec:                            # The specification of the PersistentVolume
  capacity:                      # Storage capacity of the PersistentVolume
    storage: 5Gi                 # 5Gi of storage
  accessModes:                   # Access modes for the PersistentVolume
    - ReadWriteOnce              # Can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # The policy for when the volume is released
  hostPath:                      # A simple hostPath to simulate persistent storage
    path: /mnt/data/storage       # Path to the volume on the node


### Example: `pvc-with-storage-capacity.yaml`

apiVersion: v1                  # The Kubernetes API version for Persistent Volume Claims is "v1"
kind: PersistentVolumeClaim      # We are creating a resource of type PersistentVolumeClaim
metadata:                        # Metadata contains identifying information
  name: my-storage-pvc           # The unique name of the PersistentVolumeClaim
spec:                            # The specification of the PersistentVolumeClaim
  accessModes:                   # Access modes for the PersistentVolumeClaim
    - ReadWriteOnce              # Can be mounted as read-write by a single node
  resources:                     # The requested resources for the PersistentVolumeClaim
    requests:
      storage: 5Gi               # Requesting 5Gi of storage