
# hpa.yaml
apiVersion: autoscaling/v2        # API version for HorizontalPodAutoscaler (HPA)
kind: HorizontalPodAutoscaler     # Resource type is HPA
metadata:
  name: nginx-hpa                 # Name of the HPA resource

spec:
  scaleTargetRef:                 # The workload this HPA will monitor and scale
    apiVersion: apps/v1           # Target workload API version
    kind: Deployment              # Target type: Deployment
    name: nginx-deployment        # Target name: "nginx-deployment"

  minReplicas: 1                  # Minimum number of Pods allowed
  maxReplicas: 5                  # Maximum number of Pods allowed

  metrics:                        # Metrics used for scaling
  - type: Resource                # Metric type: Resource (CPU/Memory)
    resource:
      name: cpu                   # Target metric: CPU utilization
      target:
        type: Utilization         # Scaling based on average CPU utilization %
        averageUtilization: 50    # Desired average CPU utilization across Pods = 50%




